blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/hyuniii0920/smishing-prevention-ai/discussions
    about: Please ask and answer questions in Discussions.
